name: Build Ubuntu 24.04 LTS Dev Container (Mini)
permissions:
  contents: read

on:
  push:
    branches: ["master"]
  schedule:
    - cron: "0 0 * * 1"

jobs:
  build-noble-mini-amd64:
    runs-on: ubuntu-latest
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: false
          swap-storage: false
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up QEMU (for cross-platform)
        uses: docker/setup-qemu-action@v3.7.0

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3.11.1

      - name: Log in to DockerHub
        uses: docker/login-action@v3.6.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push multi-arch image for noble (amd64)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./dockerfiles/noble_mini
          platforms: linux/amd64
          push: true
          tags: |
            theflightsims/ubuntu-dev:noble-mini-amd64

  build-noble-mini-arm64v8:
    runs-on: ubuntu-latest
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: false
          swap-storage: false
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up QEMU (for cross-platform)
        uses: docker/setup-qemu-action@v3.7.0

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3.11.1

      - name: Log in to DockerHub
        uses: docker/login-action@v3.6.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push multi-arch image for noble (arm64v8)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./dockerfiles/noble_mini
          platforms: linux/arm64/v8
          push: true
          tags: |
            theflightsims/ubuntu-dev:noble-mini-arm64v8
